{% set name = "antiSMASH" %}
{% set version = "5.0.0" %}
{% set sha256 = "0ac89aed945d2db7d8d06d8b9ead36137a05b94a211645299e0bf603968652e5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 1

source:
  url:  https://github.com/{{ name }}/{{ name }}/tree/5-0-0/{{ name }}-5-0-0.zip
  sha256: {{ sha256 }}
  patches:
    - smiles.patch  # [osx]

requirements:
  host:
    - python >=3.7
    - pip
    - icu
  run:
    - python >=3.7
    - argparse
    - bcbio-gff
    - biopython 
    - blast
    - clustalw
    - cssselect
    - diamond
    - ete2
    - fasttree
    - glimmer
    - glimmerhmm
    - hmmer
    - hmmer2
    - libxml2
    - mafft
    - matplotlib
    - meme
    - muscle
    - networkx
    - numpy
    - pandas
    - perl
    - perl-bioperl  
    - prodigal
    - pyquery
    - pysvg
    - scipy
    - scikit-learn
    - xz 

test:
  commands:
    - antismash -h

about:
  home: http://antismash.secondarymetabolites.org/
  license: AGPL-3.0
  license_family: AGPL
  license_file: LICENSE.txt
  summary: "antiSMASH allows the rapid genome-wide identification, annotation and analysis of secondary metabolite biosynthesis gene clusters."

extra:
  identifiers:
    - biotools:antismash
