{% set name = "Antismash" %}
{% set version = "5.0.alpha" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: True # [not py36]
  number: 1

source:
  path: /Users/zach/Projects/Software/antismash

requirements:
  build:
    - python

  run:
    - python
    - argparse
    - bcbiogff
    - biopython >=1.65
    - blast ==2.2.31
    - clustalw
    - cssselect
    - diamond ==0.8.36
    - ete2
    - fasttree ==2.1.9
    - glimmer ==3.02
    - glimmerhmm ==3.0.4
    - helperlibs
    - hmmer
    - hmmer2
    - openjdk
    - libxml2 ==2.9.4
    - mafft
    - matplotlib
    - meme ==4.11.2
    - muscle
    - networkx
    - numpy
    - pandas
    - prodigal
    - pyquery ==1.2.9
    - pysvg
    - scipy
    - scikit-learn ==0.18.2
    - xz


test:
  commands:
    - antismash -h

about:
  home: http://antismash.secondarymetabolites.org/
  license: GPL3
  license_file: LICENSE.txt
  summary: antiSMASH allows the rapid genome-wide identification, annotation and analysis of secondary metabolite biosynthesis gene clusters.

extra:
  identifiers:
    - biotools:antismash
