{% set name = "Antismash" %}
{% set version = "5.0.0alpha" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: True # [not py36]
  number: 0
  entry_points:
    - antismash=run_antismash:main

source:
  git_url: https://github.com/zachcp/antismash.git
  git_tag: removepyexcellerator

requirements:
  build:
    - argparse
    - bcbiogff
    - biopython >=1.71
    - cssselect
    - helperlibs
    - jinja2
    - matplotlib
    - networkx
    - numpy
    - pandas
    - pysvg-py3
    - python
    - scipy
    - scikit-learn
    - setuptools

  run:
    - python
    - argparse
    - bcbiogff
    - biopython
    - blast
    - clustalw
    - cssselect
    - diamond
    - fasttree
    - glimmer
    - glimmerhmm
    - helperlibs
    - hmmer
    - hmmer2
    - openjdk
    - libxml2
    - mafft
    - matplotlib
    - meme
    - muscle
    - networkx
    - numpy
    - pandas
    - prodigal
    - pyquery
    - setuptools
    - scipy
    - scikit-learn
    - xz


test:
  commands:
    - antismash -h

about:
  home: http://antismash.secondarymetabolites.org/
  license: GPL3
  license_file: LICENSE.txt
  summary: antiSMASH allows the rapid genome-wide identification, annotation and analysis of secondary metabolite biosynthesis gene clusters.

extra:
  identifiers:
    - biotools:antismash
