{% set name = "indigo" %}
{% set version = "1.3.0beta" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name | lower }}-{{ version }}.tar.gz
  url: https://github.com/epam/Indigo/archive/{{name | lower }}-{{ version }}.tar.gz
  md5: 37e79dd0aa7b582e3ed862ac730cd5b5



build:
  number: 0

requirements:
  build:
    - python
    - gcc   # [not osx]
    - llvm  # [osx]
  run:
    - libgcc    # [not osx]

test:
  commands:
     - indigo-depict -h  > /dev/null

about:
  home: http://lifescience.opensource.epam.com/
  license: GPL3
  summary: Universal cheminformatics library.
