package:
  name: bioconductor-dada2
  version: 1.2.1
source:
  fn: dada2_1.2.1.tar.gz
  url: http://bioconductor.org/packages/release/bioc/src/contrib/dada2_1.2.1.tar.gz
  md5: b58f336e739c1cf7a985357e24ac7de6
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biostrings >=2.32.1'
    - 'bioconductor-shortread >=1.24.0'
    - r
    - 'r-data.table >=1.9.4'
    - 'r-ggplot2 >=1.0'
    - 'r-rcpp >=0.11.2'
    - 'r-rcppparallel >=4.3.0'
    - 'r-reshape2 >=1.4.1'
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - 'bioconductor-biostrings >=2.32.1'
    - 'bioconductor-shortread >=1.24.0'
    - r
    - 'r-data.table >=1.9.4'
    - 'r-ggplot2 >=1.0'
    - 'r-rcpp >=0.11.2'
    - 'r-rcppparallel >=4.3.0'
    - 'r-reshape2 >=1.4.1'
test:
  commands:
    - '$R -e "library(''dada2'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/dada2.html
  license: LGPL-3
  summary: 'The dada2 package infers exact sequence variants (SVs) from amplicon data,
    replacing the commonly used and coarser OTU clustering approach. The dada2 pipeline
    inputs demultiplexed fastq files, and outputs the sequence variants and their
    sample-wise abundances after removing substitution and chimera errors. Taxonomic
    classification is available via a native implementation of the RDP naive Bayesian
    classifier.'
